### PR TITLE
Merged SLE-12-SP1

### PR DESCRIPTION
**Pull request by mchf**

### CODE REVIEW

**Comment by jreidinger** [comment]
LGTM

**Comment by mchf** [comment]
@jreidinger: Decreasing test coverage by 0.0% due to cleaning is not reason not to merge it in my POV. Do you agree?

**Comment by kobliha** [comment]
I do

**Comment by jreidinger** [comment]
agreed, btw it doesnn't failed due to zero but due to low coverage configrued as minimal.

**Comment by mchf** [comment]
ok, thanks

**Pull request merged**
