### PR TITLE
Revert to using separate property options to keep old tests working.

### PR DESCRIPTION
**Pull request by mvidner**
yast2-dhcp-server and yast2-samba-server log the exact command used by
us in their tests :-(

### CODE REVIEW

**Comment by mvidner** [comment]
Fixes up #613

**Comment by jreidinger** [comment]
@mvidner do you measure if there is performance difference?

**Comment by mvidner** [comment]
No. My educated guess is that the 50ms per call of systemctl is mostly spent on process startup and DBus communication. I HOPE that it doesn't try to query the properties 1 by 1 with separate DBus calls.

**Comment by mvidner** [comment]
Well, I *do* remember that I did not see any improvement  after introducing the original change in this part. So, from memory, the performance stays the same.

**Pull request merged**
