### PR TITLE
Merge of #344 into master

### PR DESCRIPTION
**Pull request by ancorgs**

### CODE REVIEW

**Comment by jreidinger** [comment]
nothing to review :)

**Comment by ancorgs** [comment]
the affected code is not longer in master, so I'm only merging to sync branches

**Comment by jreidinger** [comment]
yep, I understand and I hope my code cleaned code do not contain it :) LGTM

**Comment by ancorgs** [comment]
Don't worry, I checked it https://github.com/yast/yast-yast2/blob/master/library/packages/src/modules/PackageCallbacks.rb#L563

**Pull request merged**
