### PR TITLE
Shared RSpec examples for CWM widgets

### PR DESCRIPTION
**Pull request by mvidner**
to enable stupid but easy test coverage

### CODE REVIEW

**Comment by mvidner** [comment]
As seen in https://github.com/yast/yast-installation/pull/538

**Comment by lslezak** [comment]
@mvidner: What's the status of this? Still WIP or ready for merging? (after adding changes + version update)

**Comment by mvidner** [comment]
Thanks for the reminder, I will finalize this.

**Comment by mvidner** [comment]
I expect this to be useful for #575 (CWM::Table) and #573 (CWM::Tree) too.

**Pull request merged**
