### PR TITLE
Remove references to snapper extension

### PR DESCRIPTION
**Pull request by imobach**
* Fixes bsc#938377.

### CODE REVIEW

**Comment by ancorgs** [comment]
:+1:

**Comment by imobach** [comment]
Thanks!

**Comment by jreidinger** [comment]
so if I get it snapper is already part of insts-sys and not extension only, right?

**Comment by imobach** [comment]
@jreidinger Yes. The problem is that now we need to ship a new version of snapper because the current one does not have support for setting the clean-up algorithm nor the 'important' flag through the installation helpers.

**Comment by jreidinger** [comment]
it should be auto added when accepted to SP1 or TW, not?

**Comment by imobach** [comment]
@jreidinger I think that snapper releasing is a little bit different, isn't it? I'll take a look at what you wrote in the `README`.

@aschnell added the `--cleanup` option to installation helpers in https://github.com/openSUSE/snapper/pull/171 but we haven't released a new version since then, so the one included in the DVD is not able to do that.

**Comment by imobach** [comment]
I've take a look at OBS at it seems that they is a pending request (since 10 days ago). I'll investigate it further. Thanks!

**Pull request merged**
