### PR TITLE
Rubocop sle12 attempt2

### PR DESCRIPTION
**Pull request by jreidinger**
ready to review

### CODE REVIEW

**Comment by mvidner** [comment]
Awesome, this is much easier to review, thanks!

**Comment by mvidner** [comment]
Note to self: reviewed up to "fix unreachable code 11166dd"

**Comment by lslezak** [comment]
I'm done with the review, yeah... :zzz:

**Comment by mvidner** [comment]
Reviewed up to "use next to decrease nesting in loops 9308c86"

**Comment by mvidner** [comment]
Reviewed up to "remove semicolons 0ee8ce6".

**Comment by lslezak** [comment]
I'd say LGTM, but let's see what @mvidner finds out yet... :wink:

**Comment by mvidner** [comment]
Code looks good!
Good luck with merging to `master` :)
Please adjust the version and changelog here.

**Comment by mvidner** [comment]
LGTM

**Pull request merged**
