### PR TITLE
Firewall fix

### PR DESCRIPTION
**Pull request by jreidinger**

### CODE REVIEW

**Comment by mvidner** [comment]
CI is failing because of https://github.com/yast/yast-ruby-bindings/pull/169, we should revert that bit.

We should add a test reproducing the reported bug (importing SuSEFirewallServices before SuSEFirewall).

**Comment by jreidinger** [comment]
jenkins is now green, if you have idea how to write such bug when we load all tests via rspec and not single one due to coveralls, I will welcome this idea, but in general we need to submit this fix ASAP. So if you agree code wise, if you can LGTM it.

**Comment by ancorgs** [comment]
We are a little bit in a hurry and this is good enough. LGTM

**Comment by jreidinger** [comment]
thanks

**Pull request merged**
