### PR TITLE
Fixed clipped labels in Arabic on some widgets

### PR DESCRIPTION
**Pull request by mvidner**
https://bugzilla.suse.com/show_bug.cgi?id=880701

The actual bug seems to be between Qt and Harfbuzz. Telling Qt to use an
older Harfbuzz solves the problem.
Using that for all languages risks breaking other languages with complex
scripts (Indic?) so let's limit this to Arabic.

### CODE REVIEW

**Comment by ancorgs** [comment]
LGTM

**Comment by nilxam** [comment]
LGTM. And I will report qt5 and harfbuzz issue to upstream.

**Comment by kobliha** [comment]
Discussed offline: Martin will add reference to upstream bug here, because we need to be able to find out that the `workaround is not needed anymore`. Yast contains several similar workarounds and I'd like to keep the number of `I don't know what this does but it doesn't work without it` low. Thanks in advance.

**Comment by kobliha** [comment]
And BTW, congrats for finding and implementing this workaround! :)

**Pull request merged**
