### PR TITLE
Removed build dependency on yast2-perl-bindings (bsc#999203)

### PR DESCRIPTION
**Pull request by mvidner**
https://bugzilla.suse.com/show_bug.cgi?id=999203

The remaining 4 pm files in this package do not participate in build
time tests.

### CODE REVIEW

**Comment by jreidinger** [comment]
Please check also other build requires, e.g. libyui bindings and yast2-core looks suspicious.

**Comment by mvidner** [comment]
OK, I'll make a correct dependency graph from OBS data first (via `osc whatdependson`), so that we don't eliminate dependencies which are far from the critical path.

**Comment by jreidinger** [comment]
@mvidner I will adapt my script to generate proper output with osc whatdependson, but still I think that for future it make sense to ensure we have correct dependencies in spec file.

**Comment by mvidner** [comment]
Thanks to your script we now have [accurate dependency data](https://github.com/mvidner/rpm-build-dependencies/blob/e7143675b697dfc5bfb756a4914990b6b111e77d/yast_deps.yaml#L364).
yast2.rpm is in the 5th layer and its requirements are
```
yast2 ~ 131s:
  - libyui [0]
  - libzypp [0]
  - rubygem-cfa [0]
  - rubygem-rspec [0]
  - rubygem-rspec-core [0]
  - rubygem-rspec-expectations [0]
  - rubygem-rspec-mocks [0]
  - yast2-core [1]
  - yast2-devtools [0]
  - yast2-perl-bindings [4] # This PR removes this dependency and moves yast.rpm to layer 4
  - yast2-pkg-bindings [2]
  - yast2-ruby-bindings [3]
  - yast2-testsuite [1]
  - yast2-ycp-ui-bindings [2]
```

So the order in which we should try removing further requirements is
- yast2-ruby-bindings
- yast2-ycp-ui-bindings, yast2-pkg-bindings
- yast2-core, yast2-testsuite

I'll check that.

**Comment by mvidner** [comment]
Aaand, the ruby bindings are obviously quite hard to remove , since they contain the YCP compatibility libraries.

**Comment by jreidinger** [comment]
LGTM

**Pull request merged**
