### PR TITLE
Avoid jsc#PM-1998 and jsc#PM-2612 references

### PR DESCRIPTION
**Pull request by afaerber**
The changelog should reference jsc#SLE- ticket numbers.

### CODE REVIEW

**Review by imobachgs — APPROVED** [review]
Thanks!

**Comment by imobachgs** [comment]
And `jsc#PM-1998` is wrong too.

**Comment by suntorytimed** [comment]
As a general guidance: please use the SLE-Epic matching the targeted release.
And in case of PM-2612 keep in mind, that this is not approved yet and targeted for a new major code stream.

**Comment by afaerber** [comment]
Added a patch for jsc#PM-1998 - that one was straightforward.

**Review by imobachgs — APPROVED** [review]

**Comment by imobachgs** [comment]
Thanks @afaerber. I have opened #1197 to fix the PM-2620 reference too.

**Pull request merged**
