### PR TITLE
Removed icons from all kinds of popups (bnc#875201)

### PR DESCRIPTION
**Pull request by cwh42**
Did not do any other code cleanups although they are necessary.

### CODE REVIEW

**Comment by lslezak** [comment]
Looks good so far... thanks!

**Comment by mvidner** [comment]
Travis says:
```bash
$ rubocop
Inspecting 271 files
Offenses:
library/general/src/modules/Popup.rb:1311:16: C: Avoid comma after the last parameter of a method call.
details,
^
271 files inspected, 1 offense detected
The command "rubocop" exited with 1.
$ make -f Makefile.cvs
y2tool y2autoconf
...
```
@lslezak BTW it is quite annoying that this is hidden in the *middle* of the Travis run. Can we make it stop after it fails? And can we move Rubocop *past* the Rspec tests, while we're at it?

**Comment by cwh42** [comment]
Fixed the comma. I'll merge after Travis succeeds.

**Comment by mvidner** [comment]
Filed https://github.com/yast/yast-yast2/issues/324 for the Travis-Rubocop thing.

**Comment by lslezak** [comment]
LGTM, thanks! :+1:

**Comment by mvidner** [comment]
We have missed to remove a `nil` icon name from https://github.com/cwh42/yast-yast2/blob/785022d035438113156b10adbe4cdb477d478ff4/library/general/src/modules/Popup.rb#L1779 resulting in https://bugzilla.suse.com/show_bug.cgi?id=988739

**Pull request merged**
